name: depend
on:
  workflow_run:
      workflows: [trigger]
      types:
        - completed

# https://tech.europace.de/post/github-actions-output-variables-how-to/
  # - Get output variables between workflows

jobs:
  depend-job:
    name: DEPEND
    runs-on: ubuntu-latest
    outputs:
      mult: ${{steps.out_generator.outputs.mult}}

    steps:
      - name: print outputs 
        run: |
            echo "depend value = ${{ github.event.workflow_run.out-data.outputs.value }}"
            echo "depend value = ${{ github.event.workflow_run.trigger-job.out-data.outputs.value }}"

      - name: context sha
        run: |
            echo "context = '${{ toJSON(github.sha) }}'"
