name: depend
on:
    workflow_run:
        workflows: [trigger]
        types:
          - completed
    

jobs:
  depend-job:
    name: DEPEND
    runs-on: ubuntu-latest

    steps:
      - name: echo 
        run: |
            echo "depend value = ${{ github.event.workflow_run.out-data.outputs.value }}"
            echo "depend value = ${{ github.event.workflow_run.trigger-job.out-data.outputs.value }}"
