name: depend
on:
  workflow_run:
      workflows: [trigger]
      types:
        - completed

# https://tech.europace.de/post/github-actions-output-variables-how-to/
  # - Get output variables between workflows

jobs:
  depend-job:
    name: DEPEND
    runs-on: ubuntu-latest
    outputs:
      mult: ${{steps.out_generator.outputs.mult}}

    steps:
      - name: print outputs 
        run: |
            echo "depend value = ${{ github.event.workflow_run.trigger-job.outputs.value }}"

      - name: context
        run: |
            echo "context.sha = '${{ toJSON(github.sha) }}'"
            echo "-----------------------------------------------------------------"
            echo "context.workflow = '${{ toJSON(github.workflow) }}'"
            echo "-----------------------------------------------------------------"
            echo "context.workflow_run = '${{ toJSON(github.workflow_run) }}'"
            echo "-----------------------------------------------------------------"
            echo "context = '${{ toJSON(github.workflow_run.actor) }}'"
