name: depend
on:
    workflow_run:
        workflows: [trigger]
        types:
          - completed
    

jobs:
  depend-job:
    name: DEPEND
    runs-on: ubuntu-latest

    steps:
      - name: echo 1
        run: |
            echo "depend value = ${{ github.event.workflow_run.value }}"
            echo "depend input = ${{ github.event.workflow_run.inputs.value }}"
            echo "depend output = ${{ github.event.workflow_run.outputs.value }}"
      - name: echo 2
        run: |
            echo "depend value = ${{ github.event.workflow_run.val }}"
            echo "depend output = ${{ github.event.workflow_run.outputs.val }}"
