name: trigger
on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      value:
        type: number
        required: false
        default: 42

jobs:
  trigger-job:
    name: TRIGGER
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "trigger value = ${{ inputs.value }}"
      - name: output
        run: echo "value=${{ inputs.value }}" >> "$GITHUB_OUTPUT"
      - name: output
        run: echo "val=${{ inputs.value }}" >> $GITHUB_OUTPUT
  need-job:
    name: NEEDS
    needs: trigger-job
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "trigger value = ${{ needs.trigger-job.inputs.value }}"
          echo "trigger value = ${{ needs.trigger-job.inputs.val }}"
    
